FROM python
RUN pip install flask
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
FROM python
RUN pip install flask
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  mapquest_breakout_activity.py /home/myapp/
EXPOSE 5050
CMD python /home/myapp/mapquest_breakout_activity.py
